version: "3"

vars:
  APP_NAME: RuneCooldownTracker
  BIN_DIR: bin
  VITE_PORT: "9245"

includes:
  common: ./build/Taskfile.yml
  windows: ./build/windows/Taskfile.yml

tasks:
  default:
    cmds:
      - task: build

  build:
    cmds:
      - task: "{{OS}}:build"
        vars:
          DEV: "{{.DEV}}"

  run:
    cmds:
      - task: "{{OS}}:run"

  package:
    cmds:
      - task: "{{OS}}:package"

  dev:
    cmds:
      - wails3 dev
