// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureGraphics(arg1, arg2) {
  return window['go']['main']['App']['CaptureGraphics'](arg1, arg2);
}

export function EnableClickThrough() {
  return window['go']['main']['App']['EnableClickThrough']();
}

export function FollowWindow(arg1, arg2) {
  return window['go']['main']['App']['FollowWindow'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
