// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function CaptureGraphics(arg1:context.Context,arg2:string):Promise<void>;

export function EnableClickThrough():Promise<void>;

export function FollowWindow(arg1:context.Context,arg2:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;
